### ISSUE TITLE
Tela de Cadastro de Categoria e Checklist

### ISSUE THREAD

**Issue by marcelosilva7** [B1nary-Devs/JAIA-SOFTWARE#20]
Criação da Tela de Cadastro de Categoria realizando as seguintes tasks:
- [x] Criação das Labels
- [x] Criação dos Inputs
- [x] Criação dos Botões
