### ISSUE TITLE
Criar da classe CheckList

### ISSUE THREAD

**Issue by marcelosilva7** [B1nary-Devs/JAIA-SOFTWARE#40]
Criação da Criação da classe CheckList realizando as seguintes tasks:
- [x] Criação do Model
- [x] Criação do Repository
- [x] Criação do Service
- [x] Criacao do Controller
- [ ] Criacao do Relacionamento com a Classe Categoria
